In [19]:
"""
        @Author: parkminwoo
        @Date: 22.10.31
        @Links: 
"""

'\n        @Author: parkminwoo\n        @Date: 22.10.31\n        @Links: \n'

#### 1 Problem `1`
- 2021 Dev Matching: 웹 백엔드 개발 상반기

[example]
- rows=6, columns=6, queries=[[2,2,5,4],[3,3,6,6],[5,1,6,3]] >> result  [8, 10, 25] <br>
- rows=3, columns=3. queries=[[1,1,2,2],[1,2,2,3],[2,1,3,2],[2,2,3,3]]  >> result  [1, 1, 5, 3] <br>
- rows=100, columns=97, queries=[[1,1,100,97]]   >> result [1]

1.1 My Solution


In [20]:
import numpy as np

def get_outline_rotation(matrix, query):
    matrix = np.array(matrix)
    
    #1.상하좌우 특정
    up = matrix[(query[0]-1):query[0], (query[1]-1):query[3]][0]
    up_right = up[-1]
    bot = matrix[(query[2]-1):query[2], (query[1]-1):query[3]][0]
    bot_left = bot[-1]
    left = matrix[:,query[1]-1][query[0]-1:query[2]]
    left_up = left[1]
    right = matrix[:,query[3]-1][query[0]-1:query[2]]
    right_down = right[-2]
    
    
    #2.상하좌우 로테이션수행
    new_up_list = [left_up]
    for i in range(len(up)-1):
        new_up_list.append(up[i])
    bot_list = list(bot)
    bot_list.pop(0)
    new_bot_list = bot_list
    new_bot_list.extend([right_down])
    
    new_left_list = list(left)
    new_left_list.pop(0)
    new_left_list.append(new_bot_list[0])
    
    new_right = list(right)
    new_right.pop(-1)
    new_right_list = [new_up_list[-1]]
    new_right_list.extend(new_right)

    #3.치환
    matrix[(query[0]-1):query[0], (query[1]-1):query[3]][0] = np.array(new_up_list)
    matrix[(query[2]-1):query[2], (query[1]-1):query[3]][0] = np.array(new_bot_list)
    matrix[:,query[1]-1][query[0]-1:query[2]] = np.array(new_left_list)
    matrix[:,query[3]-1][query[0]-1:query[2]] = np.array(new_right_list)
    
    changed = new_up_list+new_bot_list+new_left_list+new_right_list
    min_val = min(changed)
    
    return matrix, min_val

## 최종함수
def solution(rows, columns, queries):
    
    answer = []
    matrix = np.array([i for i in range(1, columns*rows+1)]).reshape(rows, columns)
    
    for q in queries:
        matrix, min_val= get_outline_rotation(matrix, q)
        answer.append(min_val)
        
    answer = [int(x) for x in answer]
    
    return answer

1.2 Other's Solution


In [21]:
# 프로그래머스 박솜님
from collections import deque
def solution(rows, columns, queries):
    arr = [[i+columns*j for i in range(1,columns+1)] for j in range(rows)]
    answer, result = deque(), []
    for i in queries:
        a,b,c,d = i[0]-1,i[1]-1,i[2]-1,i[3]-1
        for x in range(d-b):
            answer.append(arr[a][b+x])
        for y in range(c-a):
            answer.append(arr[a+y][d])
        for z in range(d-b):
            answer.append(arr[c][d-z])
        for k in range(c-a):
            answer.append(arr[c-k][b])
        answer.rotate(1)
        result.append(min(answer))
        for x in range(d-b):
            arr[a][b+x] = answer[0]
            answer.popleft()
        for y in range(c-a):
            arr[a+y][d] = answer[0]
            answer.popleft()
        for z in range(d-b):
            arr[c][d-z] = answer[0]
            answer.popleft()
        for k in range(c-a):
            arr[c-k][b] = answer[0]
            answer.popleft()
    return result

In [22]:
# 프로그래머스 seyoung755 , brian6484 , 박관우 , yjincheol 님
def solution(rows, columns, queries):
    answer = []

    board = [[i+(j)*columns for i in range(1,columns+1)] for j in range(rows)]
    # print(board)

    for a,b,c,d in queries:
        stack = []
        r1, c1, r2, c2 = a-1, b-1, c-1, d-1


        for i in range(c1, c2+1):

            stack.append(board[r1][i])
            if len(stack) == 1:
                continue
            else:
                board[r1][i] = stack[-2]


        for j in range(r1+1, r2+1):
            stack.append(board[j][i])
            board[j][i] = stack[-2]

        for k in range(c2-1, c1-1, -1):
            stack.append(board[j][k])
            board[j][k] = stack[-2]

        for l in range(r2-1, r1-1, -1):
            stack.append(board[l][k])
            board[l][k] = stack[-2]

        answer.append(min(stack))


    return answer

1.3 Dummy

In [23]:
# `STEP1` matrix 생성

rows=6
columns=6

#좌표를 임베딩하기 위해 1로 채워져있는 2d list 생성(행렬)
matrix = [[1 for i in range(rows)] for j in range(columns)]
matrix

for i in range(rows):
    for j in range(columns):
        matrix[i][j] = i*rows+j+1
        
#1부터 36까지 순차적으로 채워진 rows x columns 행렬 생성

matrix

# `STEP2` 지정된 쿼리의 테두리 회전

matrix

queries = [[1,2,5,4],[3,3,6,6],[5,1,6,3]]


queries[0]


[1, 2, 5, 4]


#기대값

[[1, `8, 2, 3`, 5, 6], <br>
 [7, `14, 9, 4`, 11, 12], <br>
 [13, `20, 10, 16`, 17, 18], <br>
 [19, `26, 15, 22`, 23, 24], <br>
 [25, `27, 21, 28`, 29, 30], <br>
 [31, 32, 33, 34, 35, 36]] <br>

# `try 1`


In [24]:

query = [1,2,5,4]

#### 2.1 윗줄

matrix[0:1] #여기에서 뒤에 1이 쿼리의 0

matrix[0:1][0][2-1:4] #뒤의 2와 4가 쿼리의 1,3

#### 2.2 아랫줄

matrix[5-1:5][0] #여기에서 앞에 5가 쿼리의 3

matrix[5-1:5][0][2-1:4] #뒤의 2와 4가 쿼리의 1,3

#### 2.3 왼쪽 줄


[26, 27, 28]


- 여기서 리스트컴프리헨션이나 위치로 교체하면 너무 헷갈리겠다 그냥 처음으럼 np.array로 갔다가 2d list로 변환하자

# `try 2`
## np.array로 다시


In [25]:

import numpy as np

matrix = np.array([i for i in range(1, columns*rows+1)]).reshape(columns, rows)
matrix


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])


[1, 2, 5, 4]#기대값

[[1, `8, 2, 3`, 5, 6], <br>
 [7, `14, 9, 4`, 11, 12], <br>
 [13, `20, 10, 10`, 17, 18], <br>
 [19, `26, 15, 16`, 23, 24], <br>
 [25, `27, 28, 22`, 29, 30], <br>
 [31, 32, 33, 34, 35, 36]] <br>


In [26]:

query = [1, 2, 5, 4]

##  2.1 쿼리 위치로 특정하기

#윗줄

up = matrix[(1-1):1, (2-1):4][0]       # 쿼리의 1,3,4
print(up)

#윗줄맨우측
up_right = up[-1]
print(up_right)

#아랫줄

bot = matrix[(5-1):5, (2-1):4][0] # 쿼리의 2,3,4
print(bot)

#아래맨좌측
bot_left = bot[-1]
print(bot_left)

#맨 좌측열
left = matrix[:,2-1][1-1:5] #쿼리의 2, 1,3
print(left)

#왼쪽에 맨위
left_up = left[1]
print(left_up)

#맨 우측열
right = matrix[:,4-1][1-1:5] #쿼리의 4, 1,3
print(right)

#맨 우측 아래
right_down = right[-2]
print(right_down)

##  2.2 로테이션 코드

#윗줄 로테이션

up = matrix[(1-1):1, (2-1):4][0] #쿼리의 1,3,4
print(up)

#윗줄맨우측
up_right = up[-1]
print(up_right)

new_up_list = [left_up]

for i in range(len(up)-1):
    new_up_list.append(up[i])

new_up_list

#아래줄 로테이션

bot = matrix[(5-1):5, (2-1):4][0] # 쿼리의 2,3,4
print(bot)

#아래맨좌측
bot_left = bot[-1]
print(bot_left)

bot_list = list(bot)
bot_list.pop(0)

new_bot_list = bot_list
new_bot_list.extend([right_down])

new_bot_list

#우측줄 로테이션

#맨 우측열
right = matrix[:,4-1][1-1:5] #쿼리의 4, 1,3
print(right)

#맨 우측 아래
right_down = right[-2]
print(right_down)

new_right = list(right)

new_right.pop(-1)

new_right

new_right_list = [new_up_list[-1]]

new_right_list.extend(new_right)
new_right_list

#좌측줄 로테이션

#맨 좌측열
left = matrix[:,2-1][1-1:5] #쿼리의 2, 1,3
print(left)

#왼쪽에 맨위
left_up = left[1]
print(left_up)

new_left_list = list(left)
new_left_list.pop(0)
new_left_list.append(new_bot_list[0])

new_left_list

##  2.3 치환코드

#치환할 부분

up = matrix[(1-1):1, (2-1):4][0]   
bot = matrix[(5-1):5, (2-1):4][0] # 쿼리의 2,3,4
left = matrix[:,2-1][1-1:5] #쿼리의 2, 1,3
right = matrix[:,4-1][1-1:5] #쿼리의 4, 1,3

matrix[(1-1):1, (2-1):4][0] = np.array(new_up_list)
matrix[(5-1):5, (2-1):4][0] = np.array(new_bot_list)
matrix[:,2-1][1-1:5] = np.array(new_left_list)
matrix[:,4-1][1-1:5] = np.array(new_right_list)

matrix

#치환 결과 확인

[1, 2, 5, 4]#기대값


[2 3 4]
4
[26 27 28]
28
[ 2  8 14 20 26]
8
[ 4 10 16 22 28]
22
[2 3 4]
4
[26 27 28]
28
[ 4 10 16 22 28]
22
[ 2  8 14 20 26]
8


[1, 2, 5, 4]


[[1, `8, 2, 3`, 5, 6], <br>
 [7, `14, 9, 4`, 11, 12], <br>
 [13, `20, 15, 10`, 17, 18], <br>
 [19, `26, 21, 16`, 23, 24], <br>
 [25, `27, 28, 22`, 29, 30], <br>
 [31, 32, 33, 34, 35, 36]] <br>


In [27]:

result_sample = [[1, 8, 2, 3, 5, 6],
 [7, 14, 9, 4, 11, 12], 
 [13, 20, 15, 10, 17, 18], 
 [19, 26, 21, 16, 23, 24], 
 [25, 27, 28, 22, 29, 30], 
 [31, 32, 33, 34, 35, 36]] 

matrix == result_sample





# 함수 생성 및 테스트

query = [1, 2, 5, 4]

type(query[3])

#좌표를 임베딩하기 위해 1로 채워져있는 2d list 생성(행렬)
matrix = [[1 for i in range(rows)] for j in range(columns)]
matrix

for i in range(rows):
    for j in range(columns):
        matrix[i][j] = i*rows+j+1
        
#1부터 36까지 순차적으로 채워진 rows x columns 행렬 생성

query[0]-1

matrix = np.array(matrix)

matrix[(query[0]-1):query[0], (query[2]-1):query[3]][0]

matrix[0:1, 4:]







a = [1,2,3]
b = [3,4,5]

a+b

def get_outline_rotation(matrix, query):
    matrix = np.array(matrix)
    up = matrix[(query[0]-1):query[0], (query[1]-1):query[3]][0]
    up_right = up[-1]
    bot = matrix[(query[2]-1):query[2], (query[1]-1):query[3]][0]
    bot_left = bot[-1]
    left = matrix[:,query[1]-1][query[0]-1:query[2]]
    left_up = left[1]
    right = matrix[:,query[3]-1][query[0]-1:query[2]]
    right_down = right[-2]
    
    
    #로테이션수행
    # 상
    new_up_list = [left_up]
    for i in range(len(up)-1):
        new_up_list.append(up[i])
    
    # 하
    bot_list = list(bot)
    bot_list.pop(0)
    new_bot_list = bot_list
    new_bot_list.extend([right_down])
    
    #좌
    new_left_list = list(left)
    new_left_list.pop(0)
    new_left_list.append(new_bot_list[0])
    
    #우
    new_right = list(right)
    new_right.pop(-1)
    new_right_list = [new_up_list[-1]]
    new_right_list.extend(new_right)

    
    ##치환
    matrix[(query[0]-1):query[0], (query[1]-1):query[3]][0] = np.array(new_up_list)
    matrix[(query[2]-1):query[2], (query[1]-1):query[3]][0] = np.array(new_bot_list)
    matrix[:,query[1]-1][query[0]-1:query[2]] = np.array(new_left_list)
    matrix[:,query[3]-1][query[0]-1:query[2]] = np.array(new_right_list)
    
    changed = new_up_list+new_bot_list+new_left_list+new_right_list
    min_val = min(changed)
    
    
    return matrix, min_val

result, min_val= get_outline_rotation(matrix, query)

min_val

result_sample = [[1, 8, 2, 3, 5, 6],
 [7, 14, 9, 4, 11, 12], 
 [13, 20, 15, 10, 17, 18], 
 [19, 26, 21, 16, 23, 24], 
 [25, 27, 28, 22, 29, 30], 
 [31, 32, 33, 34, 35, 36]] 

result == result_sample







## 최종함수
def solution(rows, columns, queries):
    
    answer = []
    matrix = np.array([i for i in range(1, columns*rows+1)]).reshape(rows, columns)
    
    for q in queries:
        matrix, min_val= get_outline_rotation(matrix, q)
        answer.append(min_val)
    
    return answer

solution(6,6,[[2,2,5,4],[3,3,6,6],[5,1,6,3]])

solution(100, 97, [[1,1,100,97]])

solution(3, 3, [[1,1,2,2],[1,2,2,3],[2,1,3,2],[2,2,3,3]])

[1, 1, 5, 3]